### ISSUE TITLE
Web Access Request - Delete button

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1609]
Low Priority Issue:

Trainees cannot delete any web access requests they've submitted. The delete button is there. When it is clicked, the pop-up shows up saying "Are you sure you want to delete this web request?" and has a Cancel button and Delete button. That delete button (on the pop-up) doesn't do anything.

Preferred solution: fix the Delete button
Alternative: delete the Delete! ...until we find the preferred solution.

**Comment by Plew** [comment]
Should be fixed in PR #1612

**Comment by JoannaRumbley** [comment]
@Plew It isn't fixed yet on the live server...has it just not been updated or something?

**Comment by Plew** [comment]
Yes! it has been fixed, the server just needs to run production for the changes to take effect on live, just retested on the dev branch locally and it is fixed.
